### 1.	Write a Python Program to Add Two Matrices?

In [3]:
import numpy as np
def matrices_add(m1, m2):
    try:
        temp = np.zeros(shape = (len(m1), len(m1[0])))
        for i in range(len(m1)):
            for j in range(len(m1[0])):
                temp[i][j] = m1[i][j] + m2[i][j]
        return temp
    except:
        print("Something is wrong, ensure the matrices are of the same size and consists of integers")

In [4]:
m1 = [[1,1,1],[2,2,2],[3,3,3]]
m2 = [[4,4,4],[5,5,5],[6,6,6]]
matrices_add(m1, m2)

array([[5., 5., 5.],
       [7., 7., 7.],
       [9., 9., 9.]])

### 2.	Write a Python Program to Multiply Two Matrices?

In [5]:
import numpy as np
def matrices_multiply(mat1, mat2):
    try:
        temp2 = np.zeros(shape = (len(mat1[0]), len(mat1)))
        for i in range(len(mat1)):
            for j in range(len(mat2[0])):
                for k in range(len(mat2)):
                    temp2[i][j] += mat1[i][k] * mat2[k][j]
        return temp2      
    except Exception as e:
        print("Somthing is wrong, check the matrices dimensions", e)

In [28]:
m3 = [[1,2,3],[4,5,6],[7,8,9]]
m4 = [[4,4,4],[5,5,5],[6,6,6]]
matrices_multiply(m3, m4)

array([[ 32.,  32.,  32.],
       [ 77.,  77.,  77.],
       [122., 122., 122.]])

In [29]:
np.dot(m3,m4)

array([[ 32,  32,  32],
       [ 77,  77,  77],
       [122, 122, 122]])

### 3.	Write a Python Program to Transpose a Matrix?

In [30]:
def transposed(mat):
    temp3 = np.zeros(shape = (len(mat), len(mat[0])))
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            temp3[j][i] = mat[i][j]
    return temp3

In [31]:
transposed(m3)

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

### 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [43]:
def sort_alpha(words):
    word = words.lower().split()
    word.sort()
    return word      

In [44]:
sort_alpha("How are you kind sir, hope you had a good day. Today is a beautiful day. A beautiful sight to see.")

['a',
 'a',
 'a',
 'are',
 'beautiful',
 'beautiful',
 'day.',
 'day.',
 'good',
 'had',
 'hope',
 'how',
 'is',
 'kind',
 'see',
 'sight',
 'sir,',
 'to',
 'today',
 'you',
 'you']

### 5.	Write a Python Program to Remove Punctuation From a String?

In [121]:
import string
def remove_punc(text):
    mytable = txt.maketrans("", "", string.punctuation)
    return text.translate(mytable)

In [122]:
text = "How are you kind sir, hope you had a good day. Today is a beautiful day. A beautiful sight to see."
remove_punc(text)

'How are you kind sir hope you had a good day Today is a beautiful day A beautiful sight to see'