### 1. What are the benefits of the built-in array package, if any?

Arrays can store data very compactly and are more efficient for storing large amounts of data.
Arrays are great for numerical operations.

### 2. What are some of the array package's limitations?

The array module requires all array elements to be of the same type. Also to create an array, you'll need to specify a value type.

### 3. Describe the main differences between the array and numpy packages.

The array module requires all array elements to be of the same type. Also to create an array, you'll need to specify a value type.

On the other hand, NumPy arrays support different data types. To create a NumPy array, you only need to specify the items.

### 4. Explain the distinctions between the empty, ones, and zeros functions.

In [3]:
import numpy as np

In [5]:
# Return a new array of given shape and type, without initializing entries.
np.empty([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Return a new array of given shape and type, without initializing entries.
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
# Return a new array of given shape and type, filled with zeros.
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument?

### 6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n?

In [13]:
one = np.ones([3,3])
one + 2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

### 7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

In [14]:
one += 10
print(one)

[[11. 11. 11.]
 [11. 11. 11.]
 [11. 11. 11.]]


In [15]:
one *= 2
print(one)

[[22. 22. 22.]
 [22. 22. 22.]
 [22. 22. 22.]]


### 8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

In [16]:
np.array(['Hello'])

array(['Hello'], dtype='<U5')

In [17]:
np.array(['Hello How'])

array(['Hello How'], dtype='<U9')

In [18]:
np.array(['Hello How Are'])

array(['Hello How Are'], dtype='<U13')

In [20]:
np.array(['Hello How Are You?'])

array(['Hello How Are You?'], dtype='<U18')

### 9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

In [28]:
a = np.array([[1,3],[2,4]])

In [29]:
one + a

ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

In [33]:
b = np.array([[1,4,7],[2,5,8],[3,6,9]])

In [35]:
one + b

array([[23., 26., 29.],
       [24., 27., 30.],
       [25., 28., 31.]])

For operation like addition the dimension of the arrays should be the same. For operation like multiplication the number of columns in the first array must be equal to the number of rows in the second array.

### 10. What is the best way to use a Boolean array to mask another array?

In [42]:
X = np.array([[5, 0, 3, 3], [7, 9, 3, 5], [2, 4, 7, 6]])
X<5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [43]:
X[X<5]

array([0, 3, 3, 3, 2, 4])

### 11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

In [99]:
import time
A = np.random.rand(1000000)

In [101]:
from scipy import stats
start_time = time.time()
stats.tstd(A)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.010001659393310547 seconds ---


In [103]:
import pandas as pd
start_time = time.time()
pd.Series(A).std()
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.004003047943115234 seconds ---


In [100]:
import numpy as np
start_time = time.time()
np.std(A)
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0060045719146728516 seconds ---


In [102]:
import statistics
start_time = time.time()
statistics.stdev(A)
print("--- %s seconds ---" % (time.time() - start_time))

--- 4.862581968307495 seconds ---


### 12. What is the dimensionality of a Boolean mask-generated array?

Same as the original array from where it was generated.